### ISSUE TITLE
hw5 Problem2 b) Compute communication cost.

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#11]
[shakespeare_word_co-occurrence1.pdf](https://github.com/jasonwalker80/cse427s/files/1350713/shakespeare_word_co-occurrence1.pdf)

**Comment by bob-skowron** [comment]
I updated the tex file based on what i thought the right answer was based on the pdf. I'm going to try to run it myself though and verify.

**Comment by bob-skowron** [comment]
I'm pretty confident in the answer since the reducer inputs/outputs match and since we only have 1 reducer the shuffle & sort would ensure the # inputs match
