### ISSUE TITLE
HW6: Problem 1b

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#17]
Run on the full TrainingRatings.txt set with N=15 and add answer to written answer.

**Comment by jasonwalker80** [comment]
@bskowron23 I didn't make a pull request this time. I pushed changes to master for problem1:
https://github.com/jasonwalker80/cse427s/tree/master/hw6/problem1

**Comment by bob-skowron** [comment]
I think there are ratings without movie title maps. With your code, it bugs out (i believe due to the System.Exit(1)). So i had to modify the return to not system.exit and just do nothing.
