### ISSUE TITLE
HW6: Problem 2

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#19]
For the combiner, the input record count is: 3,192,295
The output record count is: 1,789
https://github.com/jasonwalker80/cse427s/blob/ed8172c776ba3062350c1418cf1c8d08bd8b7ef0/hw6/HW6.tex#L71

I think the answer would be 3,190,506 key,value pairs when combined.

**Comment by bob-skowron** [comment]
concur. updated
