### ISSUE TITLE
HW8: Read more on benefits of pipelining with examples.

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#24]
This is question 3 in HW8:
```
(a) Describe what pipelining means in the context of a SPARK job execution. What is its benefit?
(b) Give an example of two operations that can be pipelined together.
```

**Comment by bob-skowron** [comment]
https://jaceklaskowski.gitbooks.io/mastering-apache-spark/spark-rdd-transformations.html
http://datastrophic.io/core-concepts-architecture-and-internals-of-apache-spark/

**Comment by bob-skowron** [comment]
Latest commit i think has a better answer

**Comment by bob-skowron** [comment]
think we've got it.
