### ISSUE TITLE
HW4: Problem 1 - Part B and C

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#3]
@bskowron23 

I only noticed differences in the output, but the question specifically asks for differences in the execution.... I'll try to think about this more.
https://github.com/jasonwalker80/cse427s/blob/6bede92a61fad139eb8505ea534d2f04fc3c6b57/hw4/HW4.tex#L44
https://github.com/jasonwalker80/cse427s/blob/6bede92a61fad139eb8505ea534d2f04fc3c6b57/hw4/HW4.tex#L45

**Comment by bob-skowron** [comment]
I've responded how i think they are going. Let me know if you disagree

**Comment by jasonwalker80** [comment]
looks good to me.
