### ISSUE TITLE
Problem 3 output location

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#32]
If the output is really a print statement, I don't think the "result" goes anywhere. Although when submitted to the cluster I didn't see the output number of JPGs, so maybe that ends up in a log file on HDFS?

Reference this line:
https://github.com/jasonwalker80/cse427s/blob/57341d6b1365ebf8a53ec12ab61bbc5bb9f4f6f9/hw9/HW9.tex#L54

This is the comment on piazza regarding this question:
https://piazza.com/class/j6nxmwmqeet1zy?cid=376

**Comment by bob-skowron** [comment]
agreed. Updated in latest commit
