### ISSUE TITLE
Problem 2 Step 2: Get and Visualize synthetic location data

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#36]
```Download the synthetic clustering data from http://statistical-research.com/wp-content/ uploads/2013/11/sample_geo.txt and visualize the (latitude, longitude) pairs. You do not have to use SPARK for the visualization.```

**Comment by bob-skowron** [comment]
I used tableau public for this one. You can access via this link https://public.tableau.com/profile/bob.skowron#!/vizhome/Problem2Viz/Sheet1?publish=yes

and i uploaded a pdf as well.
