### ISSUE TITLE
Problem 3 Step 2: Understanding and Implementing k-means

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#41]
> MMDS chapter 7.3 (http://infolab.stanford.edu/~ullman/mmds/ch7.pdf) gives pseudo code and implementation strategies for the k-means clustering algorithm. Detailed implemen- tation requirements/specifications are listed below:
> The following functions will be useful for calculating k-means:
> • closestPoint:givena(latitude/longitude)pointandanarrayofcurrentcenterpoints,
> returns the index in the array of the center closest to the given point
> • addPoints: given two points, return a point which is the sum of the two points.
> • EuclideanDistance: given two points, returns the Euclidean distance of the two.
> • GreatCircleDistance: given two points, returns the great circle distance of the two.
> Note, that the addPoints function will be used to compute the new cluster centers. As we are working with spatial data given as latitude-longitude pairs implementing this function in a meaningful way will need some thought!
> The used distance measure (Euclidean or great circle), as well as the parameter k (number of clusters) should be read as an input from the command line.
> Create a variable convergeDist that will be used to decide when the k-means calculation is done, i.e. when the amount the locations of the means changes between iterations is less than convergeDist. A "perfect" solution would be 0; this number represents a "good enough" solution. For this project, use a value of 0.1.
> Parse the input file, which should also specified as a variable via the command line, into (latitude,longitude) pairs. Be sure to persist (cache) the resulting RDD because you will access it each time through the following iterations.
> Now, plan and implement the main part of the k-means algorithm. Make sure to consider an efficient implementation being aware of tasks, stages, and cached RDDs.
> When the iteration is complete, display and return the final k center points and store the k clusters (i.e., all data points plus cluster information).

**Comment by jasonwalker80** [comment]
@keon6kim if you can upload an initial version of the k-means implementation, we can discuss and review it on Github with @bskowron23.

**Comment by keon6kim** [comment]
@jasonwalker80 @bskowron23 
So I just committed what it seems like a finalized version of the k-means algorithm under 
final_project/spark

NOTE:
Part 1 of the program really depends on the format of the data that is going to be used, so it would be better written by the "key user "who really understands the format.

Part 2. This part I didn't write anything since it really depends on what we are trying to accomplish with the data.

**Comment by jasonwalker80** [comment]
Resolving.
