### ISSUE TITLE
2.1 Viz for submission

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#44]
To confirm, `2.1 Viz.PNG` is the file to be submitted to svn as `devicedata.png`?

**Comment by bob-skowron** [comment]
Correct

**Comment by keon6kim** [comment]
I believe so.

On Nov 27, 2017 10:22 AM, Jason Walker <notifications@github.com> wrote:

To confirm, 2.1 Viz.PNG is the file to be submitted to svn as devicedata.png?

**Comment by jasonwalker80** [comment]
submitted to SVN
