### ISSUE TITLE
Problem 3 Step 3: Compute and Visualize Clusters

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#47]
> In this step, you will compare the clusters using Euclidean distance vs. great circle distance. Calculate the k-means clusters for the device location data using k = 5.
> Calculate the k-means clusters for the synthetic location data using k = 2 and k = 4.
> Calculate the k-means clusters for the large-scale DBpedia location data. You will need to experiment with the number of clusters (maybe use k = 6 for a start or k = 2 or 4 if you use the US locations only). Argue, what choice of k makes sense by considering the problem context, i.e., what could the clusters actually mean/represent?
> Visualize the clusters and cluster centers (use a random subset of data points for the last dataset) for both distance measures. Can you observe a difference?

**Comment by jasonwalker80** [comment]
Run k-means and upload the following outputs:
- [x] Loudacre, Euclidean, k=5
- [x] Loudacre, GCD, k=5
- [x] DBpedia(random 10k), Euclidean, k=1-11
- [x] DBpedia(random 10k), GCD, k=1-11
- [x] DBpedia(all), Euclidean, k=1-11
- [x] DBpedia(all), GCD, k=1-11
- [x] Synthetic, Euclidean, k=2,4
- [x] Synthetic, GCD, k=2,4

**Comment by keon6kim** [comment]
@jasonwalker80 @bskowron23  I uploaded all the files. I can start working on visualization as well.
But feel free to work on them if you have time.

**Comment by keon6kim** [comment]
@jasonwalker80 @bskowron23  I uploaded all the visualizations for 3.3 to Google Drive.

For DBpedia, I realized that there are some points in Antartica mid-work. So some of the visualization, Antartica is not shown. 

Please let me know if you think this would be problematic. I can upload new ones.
