### ISSUE TITLE
Problem 3 Step 4: Runtime Analysis

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#48]
> Compare the runtime of your k-means implementation (using the same value for k) for all three datasets using the local mode with at least two threads. Further, rerun your imple- mentation without using persistent RDDs and compare those runtimes to the previously obtained ones. Create a table summarizing these results and briefly discuss your findings. After job completion you can read off the runtimes and other statistics from the Spark His- tory Server at http://localhost:18080. You might want to rerun each experiment a couple of times and use the average runtime for a more robust comparison (time permitting).

**Comment by jasonwalker80** [comment]
Use k=5 from Step 3 for each data set. With RDD persistence was run in Step 3 as well. Run once without RDD persistence for comparison of runtime performance. 

In addition to the k=5 ran in step3, run the following k=5 for fair comparison of run time, (but no google upload necessary):
- [x] Synthetic, Euclidean, k=5
- [x] Synthetic, GCD, k=5
- [x] DBpedia(random 10k), Euclidean, k=5
- [x] DBpedia(random 10k), GCD, k=5

**Comment by keon6kim** [comment]
@jasonwalker80 It seems that even for 1 data, each time I run, the run time differs by quite a bit.
So I ran each 5 times. 
I uploaded a table to the Google Drive in Google Sheets file

**Comment by jasonwalker80** [comment]
Tables added.
