### ISSUE TITLE
HW4: Problem 2 - Negative Word Count

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#5]
@bskowron23 I think this is a typo. I get 805 for the negative word count.  Also you used 805 in the s and p equations:
https://github.com/jasonwalker80/cse427s/blob/22e9722b52d3a7fcf59e96b0fc849cf8791696ab/hw4/HW4.tex#L77

**Comment by bob-skowron** [comment]
Yep will correct

**Comment by bob-skowron** [comment]
Done and uploaded to gradescope
