### ISSUE TITLE
Problem 4: Big Data and Cloud Execution

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#50]
> Can you find or crawl an even bigger dataset you want to cluster? This dataset should be bif enough that your k-means clustering computation is not feasible in your pseudo- cluster? Cluster this data by executing your SPARK program on Amazon EMR and report your results and experiences. If, you do not find another geo-location dataset, feel free to perform clustering on any other Big data clustering problem. Keep in mind that now, the interpretation and visualization of the retrieved clusters is much harder. If need be you can also use the DBpedia data in EMR.
> Document your cloud execution approach and provide the data source in your final project report. Add your pre-processing code to the src folder in your SVN repository. Describe your findings including dataset size and runtimes in your final project report.

**Comment by bob-skowron** [comment]
Notes for myself - running locally, 2016 data only, filtering for SEVPROB = 100 (10MM lines -> 20K). Takes only a couple minutes.

**Comment by bob-skowron** [comment]
@keon6kim @jasonwalker80  - for those interested, one year of data only took 5-6min to run on AWS. I uploaded to the drive a viz of 2016 data with 6 clusters. For some reason, the centroid zipWithIndex is giving different results (maybe it is partitioned differently). But it is still a pretty interesting picture .

**Comment by bob-skowron** [comment]
FYI - it does appear we're extremely subject to initial conditions. I just ran out the same sample 2x and it come up with vastly different numbers
