### ISSUE TITLE
Add new Step1 visualization

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#54]
@bskowron23 
Can you upload a PNG for the `devicedata.png` submission requirement?

**Comment by jasonwalker80** [comment]
My bad, `devicedata.png` is a screenshot of the device CSV.... 

Do we need to upload a new version? I think the only changes are line count, not formatting.

If you want to update the viz, it's now called step1.png. Feel free to close this if you don't think it's necessary. I could add it to our SVN if we do update it.

**Comment by bob-skowron** [comment]
Uploaded. Might as well include in the svn. No harm no foul i would say
