### ISSUE TITLE
Problem with creating Elbow Graph

### ISSUE THREAD

**Issue by keon6kim** [jasonwalker80/cse427s#63]
@bskowron23  So it seems like the Tableau file you uploaded on to Google drive is not calculating dist_norm and Distance Measure at all. 

I cannot output an Elbow graph without them properly working. Specifically, what is Distance Measure supposed to be?

I don't think your implementation of k-means algo outputs Distance Measure.

**Comment by jasonwalker80** [comment]
It sounds like this was resolved via GoogleDoc comments.
