### ISSUE TITLE
Upload FINAL implementation of k-means

### ISSUE THREAD

**Issue by jasonwalker80** [jasonwalker80/cse427s#64]
I noticed that the @bskowron23 version of the k-means implementation is missing the script/preprocessing logic for DBpedia data. @keon6kim can you upload the latest version of the implementation that was used for Problem 3 Step 3? 

I will need that implementation for submission of the final project.

**Comment by keon6kim** [comment]
@jasonwalker80 I just created a pull request for it.

**Comment by jasonwalker80** [comment]
New version submitted to SVN.
